# Generated by Django 4.2.25 on 2025-10-30 11:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Vendita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=255, verbose_name='Descrizione Prodotto/Servizio')),
                ('prezzo_vendita', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prezzo di Vendita (€)')),
                ('costo_acquisto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo di Acquisto (€)')),
                ('data_vendita', models.DateField(verbose_name='Data Vendita')),
                ('cliente', models.CharField(blank=True, max_length=150, null=True, verbose_name='Cliente (Opzionale)')),
                ('flag_finanziamento', models.BooleanField(default=False, verbose_name='Finanziamento Attivo')),
                ('flag_reso', models.BooleanField(default=False, verbose_name='Reso Effettuato')),
                ('flag_ritardo_consegna', models.BooleanField(default=False, verbose_name='Ritardo Consegna Segnalato')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestione.categoria', verbose_name='Categoria')),
                ('venditore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Venditore')),
            ],
            options={
                'verbose_name': 'Vendita',
                'verbose_name_plural': 'Vendite',
                'ordering': ['-data_vendita'],
            },
        ),
        migrations.CreateModel(
            name='Trattativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255, verbose_name='Titolo Trattativa')),
                ('cliente_nome', models.CharField(max_length=150, verbose_name='Nome Cliente')),
                ('cliente_contatto', models.CharField(blank=True, max_length=150, null=True, verbose_name='Email/Telefono Cliente')),
                ('valore_stimato', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valore Stimato (€)')),
                ('costo_materiali_stimato', models.DecimalField(decimal_places=2, default=0, help_text='Costo di acquisto di cucine, arredi, ecc. (COGS)', max_digits=10, verbose_name='Costo Materiali Stimato (€)')),
                ('stato', models.CharField(choices=[('LEAD', '1. Lead/Contatto'), ('APPUNTAMENTO', '2. Appuntamento Fissato'), ('PROGETTAZIONE', '3. Progettazione'), ('PREVENTIVO', '4. Preventivo Inviato'), ('IN_CONSEGNA', '5. In Consegna'), ('IN_MONTAGGIO', '6. In Montaggio'), ('VINTO', '7. Chiuso Vinto'), ('PERSO', '8. Chiuso Perso')], default='LEAD', max_length=20, verbose_name='Stato Avanzamento')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_ultimo_aggiornamento', models.DateTimeField(auto_now=True)),
                ('commerciale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trattative', to=settings.AUTH_USER_MODEL, verbose_name='Commerciale Assegnato')),
                ('vendita_collegata', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trattativa_vinta', to='gestione.vendita', verbose_name='Vendita Collegata (se vinta)')),
            ],
            options={
                'verbose_name': 'Trattativa',
                'verbose_name_plural': 'Trattative',
                'ordering': ['data_ultimo_aggiornamento'],
            },
        ),
        migrations.CreateModel(
            name='StatMensile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.PositiveIntegerField(verbose_name='Anno (es. 2024)')),
                ('mese', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mese (1-12)')),
                ('costo_marketing_mese', models.DecimalField(decimal_places=2, default=0, help_text='Costo totale delle campagne pubblicitarie per questo mese.', max_digits=10, verbose_name='Costo Marketing/Pubblicità (€)')),
                ('costi_operativi_fissi', models.DecimalField(decimal_places=2, default=0, help_text='Es. affitto, utenze, stipendi fissi (esclusi costi variabili personale).', max_digits=10, verbose_name='Costi Operativi Fissi (€)')),
                ('finanziamenti_non_approvati', models.IntegerField(default=0, help_text='Numero di richieste di finanziamento respinte.', verbose_name='Nr. Finanziamenti Non Approvati')),
            ],
            options={
                'verbose_name': 'Statistica Mensile Manuale',
                'verbose_name_plural': 'Statistiche Mensili Manuali',
                'ordering': ['-anno', '-mese'],
                'unique_together': {('anno', 'mese')},
            },
        ),
        migrations.CreateModel(
            name='ProfiloUtente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_orario', models.DecimalField(decimal_places=2, default=25.0, max_digits=5, verbose_name='Costo Orario (€)')),
                ('utente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessaggioChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messaggio', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('trattativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaggi_chat', to='gestione.trattativa')),
                ('utente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Messaggio Chat',
                'verbose_name_plural': 'Messaggi Chat',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Attivita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=255, verbose_name='Descrizione Attività')),
                ('data_attivita', models.DateField(verbose_name='Data Attività')),
                ('tempo_dedicato_ore', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Tempo Dedicato (Ore)')),
                ('note', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(blank=True, help_text='Es. Progettazione, Montaggio, Commerciale', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestione.categoria', verbose_name='Categoria Costo Servizio')),
                ('eseguita_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Eseguita da')),
                ('trattativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attivita', to='gestione.trattativa', verbose_name='Trattativa di Riferimento')),
            ],
            options={
                'verbose_name': 'Attività',
                'verbose_name_plural': 'Attività',
                'ordering': ['-data_attivita'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.PositiveIntegerField(verbose_name='Anno (es. 2024)')),
                ('mese', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mese (1-12)')),
                ('obiettivo_vendite_euro', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Budget Vendite (€)')),
                ('obiettivo_margine_percentuale', models.DecimalField(decimal_places=2, default=30.0, max_digits=5, verbose_name='Budget Margine (%)')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Budget Mensile',
                'verbose_name_plural': 'Budget Mensili',
                'ordering': ['-anno', '-mese', 'categoria'],
                'unique_together': {('anno', 'mese', 'categoria')},
            },
        ),
    ]
