# Generated by Django 4.2.25 on 2025-10-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpostazioniGenerali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soglia_alert_margine_servizio', models.DecimalField(decimal_places=2, default=20.0, help_text='Es. 20. Se il prezzo di un servizio è sotto [Costo Personale + 20%], mostra un alert.', max_digits=5, verbose_name='Soglia Alert Margine Servizi (%)')),
            ],
            options={
                'verbose_name': 'Impostazioni Generali',
                'verbose_name_plural': 'Impostazioni Generali',
            },
        ),
    ]
