# Generated by Django 4.2.25 on 2025-10-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0002_impostazionigenerali'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuoloCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome Ruolo/Squadra')),
                ('costo_orario', models.DecimalField(decimal_places=2, default=25.0, max_digits=5, verbose_name='Costo Orario Standard (€)')),
            ],
            options={
                'verbose_name': 'Ruolo (Costo Orario)',
                'verbose_name_plural': 'Ruoli (Costi Orari)',
                'ordering': ['nome'],
            },
        ),
    ]
