# Generated by Django 4.2.25 on 2025-10-30 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0003_ruolocosto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attivita',
            name='eseguita_da',
        ),
        migrations.AddField(
            model_name='attivita',
            name='ruolo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestione.ruolocosto', verbose_name='Ruolo (Costo)'),
        ),
    ]
